version: "3"
services:
    sql-server:
      image: mcr.microsoft.com/mssql/server:2019-latest
      hostname: sqlexpress
      container_name: sqlexpress
      ports:
        - "1433:1433"
      environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=Admin@123456
         - MSSQL_PID=Express
